# Generated by Django 4.1.9 on 2023-06-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='lang',
            new_name='fram',
        ),
    ]
