# Generated by Django 4.1.9 on 2023-06-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_lang_post_fram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fram',
            field=models.CharField(choices=[('0', 'django'), ('1', 'flask'), ('2', 'featured')], max_length=50),
        ),
    ]
